# Generated by Django 5.0.1 on 2024-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0023_delete_bank_remove_exchange_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='networkTo',
            field=models.CharField(max_length=100, null=True, verbose_name='Сеть'),
        ),
    ]
