# Generated by Django 5.0.1 on 2024-02-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0024_exchange_networkto'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='networkFrom',
            field=models.CharField(max_length=100, null=True, verbose_name='в сеть'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='networkTo',
            field=models.CharField(max_length=100, null=True, verbose_name='в сеть'),
        ),
    ]
