# Generated by Django 5.0.1 on 2024-02-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0025_exchange_networkfrom_alter_exchange_networkto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='exchange',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='depositsettings',
            name='crypto',
            field=models.CharField(choices=[('RUB', 'RUB')], max_length=20, null=True, verbose_name='Валюта'),
        ),
    ]
